#!/usr/bin/env python3
"""
gcode_parser.py - Fast, ultra-lightweight G-code header and metadata parser.
Optimized for Raspberry Pi Zero W (ARMv6l, single-core, low memory).
Streams line-by-line without loading entire multi-megabyte files into RAM.
"""

import re
import os
from typing import Dict, Any, Optional

# Precompiled regex patterns for maximum parsing speed
RE_T0 = re.compile(r'^\s*T0\b', re.IGNORECASE)
RE_T1 = re.compile(r'^\s*T1\b', re.IGNORECASE)
RE_TOOL_PARAM = re.compile(r'\bT([01])\b', re.IGNORECASE)
RE_TEMP_HOTEND_SET = re.compile(r'^\s*M104\b', re.IGNORECASE)
RE_TEMP_HOTEND_WAIT = re.compile(r'^\s*M109\b', re.IGNORECASE)
RE_TEMP_BED_SET = re.compile(r'^\s*M140\b', re.IGNORECASE)
RE_TEMP_BED_WAIT = re.compile(r'^\s*M190\b', re.IGNORECASE)
RE_S_VAL = re.compile(r'\bS(\d+(?:\.\d+)?)\b', re.IGNORECASE)
RE_T_VAL = re.compile(r'\bT([01])\b', re.IGNORECASE)
RE_EXTRUSION = re.compile(r'^\s*G1\b.*\bE([0-9\.\-]+)', re.IGNORECASE)

# Slicer print time comments
RE_TIME_PRUSA = re.compile(r';\s*estimated printing time(?:\s*\([^)]*\))?\s*=\s*(.*)', re.IGNORECASE)
RE_TIME_CURA = re.compile(r';\s*TIME:\s*(\d+)', re.IGNORECASE)
RE_TIME_SIMPLIFY = re.compile(r';\s*Build time:\s*(.*)', re.IGNORECASE)
RE_TIME_FLASHPRINT = re.compile(r';\s*(?:estimated|print)\s*time:\s*(.*)', re.IGNORECASE)
RE_TIME_ORCA = re.compile(r';\s*total estimated time\s*=\s*(.*)', re.IGNORECASE)
RE_SLICER_NAME = re.compile(r';\s*(?:generated by|Sliced at|Producer:)\s*(.*)', re.IGNORECASE)

# Slicer comments for tools & temperatures
RE_PRUSA_EXTRUDERS = re.compile(r';\s*extruder_filament\s*=\s*(.*)', re.IGNORECASE)
RE_CURA_EXTRUDER = re.compile(r';\s*Extruder\s*([01])\b', re.IGNORECASE)
RE_FLASHPRINT_R_MAT = re.compile(r';\s*right_extruder_material\s*:\s*(.*)', re.IGNORECASE)
RE_FLASHPRINT_L_MAT = re.compile(r';\s*left_extruder_material\s*:\s*(.*)', re.IGNORECASE)


def parse_time_seconds(time_str: str) -> Optional[int]:
    """Parse time string like '1h 25m 30s' or '45m' into total seconds."""
    if not time_str:
        return None
    time_str = time_str.strip()
    
    # Try format "HH:MM:SS" or "MM:SS"
    if ':' in time_str:
        parts = time_str.split(':')
        try:
            if len(parts) == 3:
                return int(parts[0]) * 3600 + int(parts[1]) * 60 + int(float(parts[2]))
            elif len(parts) == 2:
                return int(parts[0]) * 60 + int(float(parts[1]))
        except ValueError:
            pass

    # Try "1h 23m 45s", "1 hour 20 minutes", "45m"
    hours = 0
    minutes = 0
    seconds = 0
    h_match = re.search(r'(\d+)\s*(?:h|hour|hours)', time_str, re.IGNORECASE)
    m_match = re.search(r'(\d+)\s*(?:m|min|minute|minutes)', time_str, re.IGNORECASE)
    s_match = re.search(r'(\d+)\s*(?:s|sec|second|seconds)', time_str, re.IGNORECASE)

    found = False
    if h_match:
        hours = int(h_match.group(1))
        found = True
    if m_match:
        minutes = int(m_match.group(1))
        found = True
    if s_match:
        seconds = int(s_match.group(1))
        found = True

    if found:
        return hours * 3600 + minutes * 60 + seconds
    
    # Check if purely digits (e.g. Cura seconds)
    if time_str.isdigit():
        return int(time_str)

    return None


def format_duration(seconds: Optional[int]) -> str:
    """Format seconds into human readable duration like '1h 24m' or '35m'."""
    if seconds is None or seconds <= 0:
        return "Unknown"
    h = seconds // 3600
    m = (seconds % 3600) // 60
    s = seconds % 60
    if h > 0:
        return f"{h}h {m}m" if m > 0 else f"{h}h"
    elif m > 0:
        return f"{m}m {s}s" if s > 0 else f"{m}m"
    else:
        return f"{s}s"


def inspect_gcode_file(filepath: str, max_header_lines: int = 5000) -> Dict[str, Any]:
    """
    Inspect a G-code file to extract:
    - Target extruder ('Right (T0)', 'Left (T1)', or 'Both (T0 & T1)')
    - Target temperatures (T0, T1, Bed)
    - Estimated print time
    - Total line count and file size in bytes
    """
    file_size = 0
    try:
        file_size = os.path.getsize(filepath)
    except OSError:
        pass

    tools_detected = set()
    current_tool = 0
    extruded_tools = set()
    target_temps = {
        "tool0": 0.0,
        "tool1": 0.0,
        "bed": 0.0
    }
    estimated_seconds = None
    slicer_name = "Unknown"
    total_lines = 0

    flashprint_right = False
    flashprint_left = False

    with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
        for idx, line in enumerate(f):
            total_lines += 1
            raw = line.strip()
            if not raw:
                continue

            # Check slicer comments (mostly in the header or footer)
            if raw.startswith(';'):
                if not slicer_name or slicer_name == "Unknown":
                    m_slicer = RE_SLICER_NAME.search(raw)
                    if m_slicer:
                        slicer_name = m_slicer.group(1).strip()

                # Print time detection
                if estimated_seconds is None:
                    m_prusa = RE_TIME_PRUSA.search(raw)
                    if m_prusa:
                        estimated_seconds = parse_time_seconds(m_prusa.group(1))
                    else:
                        m_cura = RE_TIME_CURA.search(raw)
                        if m_cura:
                            estimated_seconds = int(m_cura.group(1))
                        else:
                            m_simplify = RE_TIME_SIMPLIFY.search(raw)
                            if m_simplify:
                                estimated_seconds = parse_time_seconds(m_simplify.group(1))
                            else:
                                m_fp = RE_TIME_FLASHPRINT.search(raw)
                                if m_fp:
                                    estimated_seconds = parse_time_seconds(m_fp.group(1))
                                else:
                                    m_orca = RE_TIME_ORCA.search(raw)
                                    if m_orca:
                                        estimated_seconds = parse_time_seconds(m_orca.group(1))

                # Tool comments
                m_fp_r = RE_FLASHPRINT_R_MAT.search(raw)
                if m_fp_r and m_fp_r.group(1).strip().lower() not in ('none', 'null', ''):
                    flashprint_right = True
                m_fp_l = RE_FLASHPRINT_L_MAT.search(raw)
                if m_fp_l and m_fp_l.group(1).strip().lower() not in ('none', 'null', ''):
                    flashprint_left = True

                continue

            # G-code command parsing
            # Tool change
            if RE_T0.match(raw):
                current_tool = 0
                tools_detected.add(0)
            elif RE_T1.match(raw):
                current_tool = 1
                tools_detected.add(1)

            # Check extrusion commands
            if RE_EXTRUSION.search(raw):
                extruded_tools.add(current_tool)

            # Hotend temp set (M104 or M109)
            if RE_TEMP_HOTEND_SET.match(raw) or RE_TEMP_HOTEND_WAIT.match(raw):
                s_match = RE_S_VAL.search(raw)
                t_match = RE_T_VAL.search(raw)
                if s_match:
                    temp_val = float(s_match.group(1))
                    target_tool = int(t_match.group(1)) if t_match else current_tool
                    if temp_val > 0:
                        tools_detected.add(target_tool)
                        if target_tool == 0 and target_temps["tool0"] == 0:
                            target_temps["tool0"] = temp_val
                        elif target_tool == 1 and target_temps["tool1"] == 0:
                            target_temps["tool1"] = temp_val

            # Bed temp set (M140 or M190)
            if RE_TEMP_BED_SET.match(raw) or RE_TEMP_BED_WAIT.match(raw):
                s_match = RE_S_VAL.search(raw)
                if s_match and target_temps["bed"] == 0:
                    target_temps["bed"] = float(s_match.group(1))

    # Determine primary extruder description
    active_tools = extruded_tools or tools_detected
    if flashprint_right and flashprint_left:
        active_tools = {0, 1}
    elif flashprint_right and not flashprint_left:
        active_tools.add(0)
    elif flashprint_left and not flashprint_right:
        active_tools.add(1)

    if 0 in active_tools and 1 in active_tools:
        tool_desc = "Both (T0 & T1)"
        tool_code = "T0+T1"
    elif 1 in active_tools:
        tool_desc = "Left (T1)"
        tool_code = "T1"
    else:
        # Default for FlashForge Creator Pro is Right Extruder (T0)
        tool_desc = "Right (T0)"
        tool_code = "T0"

    formatted_time = format_duration(estimated_seconds)

    return {
        "tool": tool_desc,
        "tool_code": tool_code,
        "target_temps": target_temps,
        "estimated_time": formatted_time,
        "estimated_seconds": estimated_seconds,
        "total_lines": total_lines,
        "file_size_bytes": file_size,
        "slicer": slicer_name
    }


if __name__ == '__main__':
    import sys
    if len(sys.argv) > 1:
        res = inspect_gcode_file(sys.argv[1])
        print("Inspection Results:")
        for k, v in res.items():
            print(f"  {k}: {v}")
    else:
        print("Usage: gcode_parser.py <path_to_file.gcode>")
