; generated by PrusaSlicer 2.6.0 for FlashForge Creator Pro
; estimated printing time (normal mode) = 28m 14s
; filament used [mm] = 2450.5
; filament used [cm3] = 5.89
; filament used [g] = 7.36
; filament cost = 0.15
; total layers count = 100
;
; Slicer Settings Summary:
; temperature = 205
; bed_temperature = 60
; first_layer_temperature = 210
; first_layer_bed_temperature = 60
; extruder_filament = PLA

; --- Start G-code for FlashForge Creator Pro (Sailfish) ---
M140 S60 ; Set target bed temperature
M190 S60 ; Wait for bed to reach temperature
M104 T0 S205 ; Set target nozzle temperature
M109 T0 S205 ; Wait for nozzle to reach temperature

G28 ; Home all axes
G92 E0 ; Reset extruder position
G1 Z0.4 F1200 ; Lift nozzle
G1 X-100 Y-70 F3000 ; Move to front left corner
G1 X-60 E5.0 F1000 ; Prime line extrusion
G92 E0 ; Reset extrusion

; --- Model Layer 1 ---
T0 ; Select Right Extruder
G1 F1800
G1 X10.0 Y10.0 Z0.2 E0.5
G1 X20.0 Y10.0 E1.0
G1 X20.0 Y20.0 E1.5
G1 X10.0 Y20.0 E2.0
G1 X10.0 Y10.0 E2.5

; --- Model Layer 2 ---
G1 Z0.4 F1200
G1 X10.0 Y10.0 E2.6
G1 X20.0 Y10.0 E3.1
G1 X20.0 Y20.0 E3.6
G1 X10.0 Y20.0 E4.1
G1 X10.0 Y10.0 E4.6

; --- End G-code ---
M104 T0 S0 ; Turn off right hotend
M104 T1 S0 ; Turn off left hotend
M140 S0 ; Turn off heated bed
G91 ; Relative coordinates
G1 Z10 F1000 ; Lower bed 10mm
G90 ; Absolute coordinates
G28 X Y ; Home/park X and Y axes
M84 ; Disable stepper motors
